import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'storage_service.dart';

class ChatMessage {
  final String id;
  final String text;
  final String senderId;
  final String senderName;
  final String conversationId;
  final DateTime timestamp;

  ChatMessage({
    required this.id, 
    required this.text, 
    required this.senderId, 
    required this.senderName,
    required this.conversationId,
    required this.timestamp,
  });

  Map<String, dynamic> toFirestore() {
    return {
      'text': text,
      'senderId': senderId,
      'senderName': senderName,
      'conversationId': conversationId,
      'timestamp': Timestamp.fromDate(timestamp),
    };
  }

  factory ChatMessage.fromFirestore(String id, Map<String, dynamic> data) {
    return ChatMessage(
      id: id,
      text: data['text'] ?? '',
      senderId: data['senderId'] ?? '',
      senderName: data['senderName'] ?? 'User',
      conversationId: data['conversationId'] ?? 'default',
      timestamp: (data['timestamp'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }
}


class ChatService extends ChangeNotifier {
  static final ChatService _instance = ChatService._internal();
  factory ChatService() => _instance;
  ChatService._internal();

  List<ChatMessage> _messages = [];
  bool _initialized = false;

  final FirebaseFirestore _db = FirebaseFirestore.instance;

  Future<void> init() async {
    if (_initialized) return;
    
    // Listen to ALL messages (optimally we'd query by user's conversations, but for this demo this is fine)
    _db.collection('messages').orderBy('timestamp').snapshots().listen((snapshot) {
      _messages = snapshot.docs.map((doc) {
        return ChatMessage.fromFirestore(doc.id, doc.data());
      }).toList();
      notifyListeners();
    });
    
    _initialized = true;
  }

  List<ChatMessage> getMessages(String conversationId) {
    return _messages.where((m) => m.conversationId == conversationId).toList();
  }
  
  // Get all conversation IDs for a user (either sender or part of ID)
  // Convention: conversationId = "driverId_hostId"
  List<String> getConversationsForUser(String userId) {
    // If I am driver, my ID is first part. If host, second part.
    // Simplifying: just check if ID is in the string? 
    // Or better: filter unique conversationIds where userId matches one of the participants.
    // For now, let's just return all unique IDs that contain the userId?
    // Actually, distinct conversationIds.
    return _messages.map((m) => m.conversationId).toSet().where((id) => id.contains(userId)).toList();
  }

  Future<void> sendMessage(String text, String senderId, String senderName, String conversationId) async {
    final msg = ChatMessage(
      id: '', // Generated by Firestore
      text: text,
      senderId: senderId,
      senderName: senderName,
      conversationId: conversationId,
      timestamp: DateTime.now(),
    );
    
    await _db.collection('messages').add(msg.toFirestore());
    
    // TASK 2 FIX: Update lastMessageAt so conversation appears at top of list
    // and is visible to both parties
    await _db.collection('conversations').doc(conversationId).update({
      'lastMessageAt': Timestamp.now(),
    }).catchError((_) {
      // Ignore if conversation doc doesn't exist yet
    });
  }

  // Create a conversation when booking is made
  // TASK 2: Each conversation is tied to a specific parking spot (spotId)
  Future<String> createConversationForBooking({
    required String driverId,
    required String driverName,
    required String hostId,
    required String hostName,
    required String spotId, // TASK 2: Per-parking messaging
    required String spotTitle,
    required String bookingId,
  }) async {
    // TASK 2: Convention: conversationId = "driverId_hostId_spotId_bookingId"
    // This ensures each parking spot has its own chat thread
    final conversationId = '${driverId}_${hostId}_${spotId}_$bookingId';
    
    // Send initial system message
    final initialMsg = ChatMessage(
      id: '',
      text: '🅿️ Νέα κράτηση για "$spotTitle"! Μπορείτε να επικοινωνήσετε εδώ.',
      senderId: 'system',
      senderName: 'ParkNow',
      conversationId: conversationId,
      timestamp: DateTime.now(),
    );
    
    await _db.collection('messages').add(initialMsg.toFirestore());
    
    // Store conversation metadata for easy lookup (TASK 2: includes spotId)
    await _db.collection('conversations').doc(conversationId).set({
      'driverId': driverId,
      'driverName': driverName,
      'hostId': hostId,
      'hostName': hostName,
      'spotId': spotId, // TASK 2: Store spotId for per-parking filtering
      'spotTitle': spotTitle,
      'bookingId': bookingId,
      'createdAt': Timestamp.now(),
      'lastMessageAt': Timestamp.now(),
    });
    
    return conversationId;
  }

  // Get conversations where user is participant (as driver or host)
  Future<List<Map<String, dynamic>>> getConversationsForUserAsync(String userId) async {
    // Query where user is driver
    final asDriver = await _db.collection('conversations')
        .where('driverId', isEqualTo: userId)
        .get();
    
    // Query where user is host
    final asHost = await _db.collection('conversations')
        .where('hostId', isEqualTo: userId)
        .get();
    
    final all = [...asDriver.docs, ...asHost.docs];
    return all.map((doc) => {'id': doc.id, ...doc.data()}).toList();
  }

  // Get conversations where user is HOST only (for host mode messages view)
  Future<List<Map<String, dynamic>>> getConversationsForHost(String userId) async {
    try {
      // TASK 3 FIX: Removed orderBy to avoid composite index requirement
      final asHost = await _db.collection('conversations')
          .where('hostId', isEqualTo: userId)
          .get();
      
      final results = asHost.docs.map((doc) => {'id': doc.id, ...doc.data()}).toList();
      
      // Sort in memory instead of in query to avoid index issues
      results.sort((a, b) {
        final aTime = (a['lastMessageAt'] as Timestamp?)?.toDate() ?? DateTime(1970);
        final bTime = (b['lastMessageAt'] as Timestamp?)?.toDate() ?? DateTime(1970);
        return bTime.compareTo(aTime); // Descending
      });
      
      return results;
    } catch (e) {
      debugPrint('Error fetching host conversations: $e');
      return [];
    }
  }

  // Get conversations where user is DRIVER only (for user mode messages view)
  Future<List<Map<String, dynamic>>> getConversationsForDriver(String userId) async {
    try {
      // TASK 3 FIX: Removed orderBy to avoid composite index requirement
      final asDriver = await _db.collection('conversations')
          .where('driverId', isEqualTo: userId)
          .get();
      
      final results = asDriver.docs.map((doc) => {'id': doc.id, ...doc.data()}).toList();
      
      // Sort in memory instead of in query to avoid index issues
      results.sort((a, b) {
        final aTime = (a['lastMessageAt'] as Timestamp?)?.toDate() ?? DateTime(1970);
        final bTime = (b['lastMessageAt'] as Timestamp?)?.toDate() ?? DateTime(1970);
        return bTime.compareTo(aTime); // Descending
      });
      
      return results;
    } catch (e) {
      debugPrint('Error fetching driver conversations: $e');
      return [];
    }
  }

  // Check if this is the first user message in a conversation (for auto-reply trigger)
  Future<bool> isFirstUserMessage(String conversationId, String driverId) async {
    final messages = await _db.collection('messages')
        .where('conversationId', isEqualTo: conversationId)
        .where('senderId', isEqualTo: driverId)
        .limit(1)
        .get();
    
    return messages.docs.isEmpty;
  }

  // Send automated reply from host
  Future<void> sendAutoReply(String conversationId, String hostId, String hostName) async {
    final autoReply = ChatMessage(
      id: '',
      text: 'Ευχαριστώ για το ενδιαφέρον σας! Θα απαντήσω σύντομα. 🅿️',
      senderId: hostId,
      senderName: hostName,
      conversationId: conversationId,
      timestamp: DateTime.now(),
    );
    
    await _db.collection('messages').add(autoReply.toFirestore());
    
    // Update last message timestamp
    await _db.collection('conversations').doc(conversationId).update({
      'lastMessageAt': Timestamp.now(),
      'hasAutoReplied': true,
    });
  }

  // Check if auto-reply was already sent
  Future<bool> hasAutoReplied(String conversationId) async {
    final doc = await _db.collection('conversations').doc(conversationId).get();
    return doc.data()?['hasAutoReplied'] == true;
  }

  // Send message with auto-reply trigger for first user message
  Future<void> sendMessageWithAutoReply({
    required String text,
    required String senderId,
    required String senderName,
    required String conversationId,
    String? hostId,
    String? hostName,
  }) async {
    // Send the actual message
    await sendMessage(text, senderId, senderName, conversationId);
    
    // Check if this warrants an auto-reply (first message from driver to host)
    if (hostId != null && hostName != null && senderId != hostId) {
      final alreadyReplied = await hasAutoReplied(conversationId);
      if (!alreadyReplied) {
        // Small delay to make it feel more natural
        await Future.delayed(const Duration(milliseconds: 500));
        await sendAutoReply(conversationId, hostId, hostName);
      }
    }
  }
}
