import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'storage_service.dart';

class ChatMessage {
  final String id;
  final String text;
  final String senderId;
  final String senderName;
  final String conversationId;
  final DateTime timestamp;

  ChatMessage({
    required this.id, 
    required this.text, 
    required this.senderId, 
    required this.senderName,
    required this.conversationId,
    required this.timestamp,
  });

  Map<String, dynamic> toFirestore() {
    return {
      'text': text,
      'senderId': senderId,
      'senderName': senderName,
      'conversationId': conversationId,
      'timestamp': Timestamp.fromDate(timestamp),
    };
  }

  factory ChatMessage.fromFirestore(String id, Map<String, dynamic> data) {
    return ChatMessage(
      id: id,
      text: data['text'] ?? '',
      senderId: data['senderId'] ?? '',
      senderName: data['senderName'] ?? 'User',
      conversationId: data['conversationId'] ?? 'default',
      timestamp: (data['timestamp'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }
}


class ChatService extends ChangeNotifier {
  static final ChatService _instance = ChatService._internal();
  factory ChatService() => _instance;
  ChatService._internal();

  List<ChatMessage> _messages = [];
  bool _initialized = false;

  final FirebaseFirestore _db = FirebaseFirestore.instance;

  Future<void> init() async {
    if (_initialized) return;
    
    // Listen to ALL messages (optimally we'd query by user's conversations, but for this demo this is fine)
    _db.collection('messages').orderBy('timestamp').snapshots().listen((snapshot) {
      _messages = snapshot.docs.map((doc) {
        return ChatMessage.fromFirestore(doc.id, doc.data());
      }).toList();
      notifyListeners();
    });
    
    _initialized = true;
  }

  List<ChatMessage> getMessages(String conversationId) {
    return _messages.where((m) => m.conversationId == conversationId).toList();
  }
  
  // Get all conversation IDs for a user (either sender or part of ID)
  // Convention: conversationId = "driverId_hostId"
  List<String> getConversationsForUser(String userId) {
    // If I am driver, my ID is first part. If host, second part.
    // Simplifying: just check if ID is in the string? 
    // Or better: filter unique conversationIds where userId matches one of the participants.
    // For now, let's just return all unique IDs that contain the userId?
    // Actually, distinct conversationIds.
    return _messages.map((m) => m.conversationId).toSet().where((id) => id.contains(userId)).toList();
  }

  Future<void> sendMessage(String text, String senderId, String senderName, String conversationId) async {
    final msg = ChatMessage(
      id: '', // Generated by Firestore
      text: text,
      senderId: senderId,
      senderName: senderName,
      conversationId: conversationId,
      timestamp: DateTime.now(),
    );
    
    await _db.collection('messages').add(msg.toFirestore());
  }

  // Create a conversation when booking is made
  Future<String> createConversationForBooking({
    required String driverId,
    required String driverName,
    required String hostId,
    required String hostName,
    required String spotTitle,
    required String bookingId,
  }) async {
    // Convention: conversationId = "driverId_hostId_bookingId"
    final conversationId = '${driverId}_${hostId}_$bookingId';
    
    // Send initial system message
    final initialMsg = ChatMessage(
      id: '',
      text: '🅿️ Νέα κράτηση για "$spotTitle"! Μπορείτε να επικοινωνήσετε εδώ.',
      senderId: 'system',
      senderName: 'ParkNow',
      conversationId: conversationId,
      timestamp: DateTime.now(),
    );
    
    await _db.collection('messages').add(initialMsg.toFirestore());
    
    // Also store conversation metadata for easy lookup
    await _db.collection('conversations').doc(conversationId).set({
      'driverId': driverId,
      'driverName': driverName,
      'hostId': hostId,
      'hostName': hostName,
      'spotTitle': spotTitle,
      'bookingId': bookingId,
      'createdAt': Timestamp.now(),
      'lastMessageAt': Timestamp.now(),
    });
    
    return conversationId;
  }

  // Get conversations where user is participant (as driver or host)
  Future<List<Map<String, dynamic>>> getConversationsForUserAsync(String userId) async {
    // Query where user is driver
    final asDriver = await _db.collection('conversations')
        .where('driverId', isEqualTo: userId)
        .get();
    
    // Query where user is host
    final asHost = await _db.collection('conversations')
        .where('hostId', isEqualTo: userId)
        .get();
    
    final all = [...asDriver.docs, ...asHost.docs];
    return all.map((doc) => {'id': doc.id, ...doc.data()}).toList();
  }
}
